# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  - group: sonar-scanner-vsts-variables
  - name: System.debug
    value: true

stages:
- stage: build
  displayName: 'Build:'
  jobs:
  - job: npminstall
    displayName: 'NPM Install, CI and Build'
    variables:
      publisher: $(SonarSourceITPublisher)
    steps:
    - task: Npm@1
      displayName: 'Update npm'
      inputs:
        command: 'custom'
        customCommand: 'i -g npm@latest'

    - task: Npm@1
      displayName: 'Install dependencies'
      inputs:
        command: 'install'

    - task: Npm@1
      displayName: 'Install all dependencies'
      inputs:
        command: 'custom'
        customCommand: 'run install-dep-full'

    - task: Npm@1
      displayName: 'Run Validate-CI'
      inputs:
        command: 'custom'
        customCommand: 'run validate-ci'

  

    - task: Npm@1
      displayName: 'Create test extension'
      inputs:
        command: 'custom'
        customCommand: 'run test-build -- --publisher $(publisher)'

    - task: CopyFiles@2
      displayName: 'Copy artefacts to build directory'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/build'
        Contents: '*.vsix'
        TargetFolder: '$(Agent.BuildDirectory)/a'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifacts on the build'
      inputs:
        PathtoPublish: '$(Agent.BuildDirectory)/a'
        ArtifactName: 'extensions'

